from fastapi import FastAPI, UploadFile, File, Form, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from fastapi.responses import FileResponse
import pandas as pd
from automl.engine import run_automl_pipeline
from fastapi.staticfiles import StaticFiles
from fastapi.responses import RedirectResponse
import os
from datetime import datetime
from uuid import uuid4
from urllib.parse import unquote
import joblib
app = FastAPI()


# Get absolute path (VERY IMPORTANT for Render)
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
UI_PATH = os.path.join(BASE_DIR, "automl-ui")
MODELS_DIR = os.path.join(BASE_DIR, "trained_models")
os.makedirs(MODELS_DIR, exist_ok=True)

# Tracks model files generated by API runs.
MODEL_REGISTRY = {}

# Redirect root → UI
@app.get("/")
def root():
    return RedirectResponse(url="/app")

# Enable CORS for frontend with more permissive settings
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Allow all origins (for development)
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Health check endpoint
@app.get("/health")
async def health():
    return {"status": "ok", "message": "Backend is running"}

@app.post("/automl")
async def run_automl(
    file: UploadFile = File(...),
    target_column: str = Form(...)
):
    try:

        df = pd.read_csv(file.file)

        output = run_automl_pipeline(df, target_column)

        results = output["results"]

        model_scores = {
            name: score for name,(model,score) in results.items()
        }

        best_model_name = output["best_model"]
        best_model_obj = output["results"][best_model_name][0]

        run_id = str(uuid4())
        timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        model_filename = f"best_model_{timestamp}_{run_id}.pkl"
        model_path = os.path.join(MODELS_DIR, model_filename)
        joblib.dump(best_model_obj, model_path)

        MODEL_REGISTRY[run_id] = {
            "path": model_path,
            "filename": model_filename,
            "best_model": best_model_name
        }

        return {
            "best_model": output["best_model"],
            "best_score": output["best_score"],
            "models": model_scores,
            "report": output["report"],
            "run_id": run_id,
            "model_download_url": f"/automl/download/{run_id}"
        }

    except Exception as e:
        print(f"Error: {str(e)}")  # Log to console
        import traceback
        traceback.print_exc()
        return JSONResponse(
            status_code=500,
            content={"error": str(e), "type": type(e).__name__}
        )

@app.get("/automl/download/{run_ref:path}")
async def download_best_model(run_ref: str):
    # Accept either plain run_id or a pasted URL/path and normalize to the UUID token.
    normalized = unquote(run_ref).strip().strip("/")
    if "/" in normalized:
        normalized = normalized.split("/")[-1]

    run_id = normalized
    model_info = MODEL_REGISTRY.get(run_id)
    if not model_info:
        raise HTTPException(status_code=404, detail="Model not found for this run_id")

    if not os.path.exists(model_info["path"]):
        raise HTTPException(status_code=404, detail="Model file no longer exists on server")

    return FileResponse(
        path=model_info["path"],
        filename=model_info["filename"],
        media_type="application/octet-stream"
    )

app.mount("/app", StaticFiles(directory="automl-ui", html=True), name="ui")
